<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FTIU28S" failures="3" tests="15" name="TestNGPack.VerifyLoginPage" time="110.852" errors="0" timestamp="2023-03-31T12:57:22 IST" skipped="3">
  <testcase classname="TestNGPack.VerifyLoginPage" name="verifyTextPresentOnUserName" time="6.845"/>
  <system-out/>
  <testcase classname="TestNGPack.VerifyLoginPage" name="verifyTextPresentOnUserName" time="1.137"/>
  <system-out/>
  <testcase classname="TestNGPack.VerifyLoginPage" name="verifyTextPresentOnUserName" time="1.879"/>
  <system-out/>
  <testcase classname="TestNGPack.VerifyLoginPage" name="verifyErrorMessageOfIncorrectPassword" time="14.868"/>
  <system-out/>
  <testcase classname="TestNGPack.VerifyLoginPage" name="verifyErrorMessageOfIncorrectPassword" time="16.577"/>
  <system-out/>
  <testcase classname="TestNGPack.VerifyLoginPage" name="verifyErrorMessageOfIncorrectPassword" time="6.558"/>
  <system-out/>
  <testcase classname="TestNGPack.VerifyLoginPage" name="verifyErrorMessageOfIncorrectUserName" time="8.111"/>
  <system-out/>
  <testcase classname="TestNGPack.VerifyLoginPage" name="verifyErrorMessageOfIncorrectUserName" time="16.490"/>
  <system-out/>
  <testcase classname="TestNGPack.VerifyLoginPage" name="verifyErrorMessageOfIncorrectUserName" time="11.591"/>
  <system-out/>
  <testcase classname="TestNGPack.VerifyLoginPage" name="verifyForgotPasswordLinkOnLoginPage" time="11.715">
    <failure message="expected [https://www.facebook.com/] but found [https://www.facebook.com/recover/initiate/?privacy_mutation_token=eyJ0eXBlIjowLCJjcmVhdGlvbl90aW1lIjoxNjgwMjQ3NTk1LCJjYWxsc2l0ZV9pZCI6MzgxMjI5MDc5NTc1OTQ2fQ%3D%3D&amp;ars=facebook_login]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.facebook.com/] but found [https://www.facebook.com/recover/initiate/?privacy_mutation_token=eyJ0eXBlIjowLCJjcmVhdGlvbl90aW1lIjoxNjgwMjQ3NTk1LCJjYWxsc2l0ZV9pZCI6MzgxMjI5MDc5NTc1OTQ2fQ%3D%3D&ars=facebook_login]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at TestNGPack.VerifyLoginPage.verifyForgotPasswordLinkOnLoginPage(VerifyLoginPage.java:151)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyForgotPasswordLinkOnLoginPage -->
  <system-out/>
  <testcase classname="TestNGPack.VerifyLoginPage" name="verifyForgotPasswordLinkOnLoginPage" time="5.665">
    <failure message="expected [https://www.facebook.com/] but found [https://www.facebook.com/recover/initiate/?privacy_mutation_token=eyJ0eXBlIjowLCJjcmVhdGlvbl90aW1lIjoxNjgwMjQ3NjE5LCJjYWxsc2l0ZV9pZCI6MzgxMjI5MDc5NTc1OTQ2fQ%3D%3D&amp;ars=facebook_login]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.facebook.com/] but found [https://www.facebook.com/recover/initiate/?privacy_mutation_token=eyJ0eXBlIjowLCJjcmVhdGlvbl90aW1lIjoxNjgwMjQ3NjE5LCJjYWxsc2l0ZV9pZCI6MzgxMjI5MDc5NTc1OTQ2fQ%3D%3D&ars=facebook_login]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at TestNGPack.VerifyLoginPage.verifyForgotPasswordLinkOnLoginPage(VerifyLoginPage.java:151)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyForgotPasswordLinkOnLoginPage -->
  <system-out/>
  <testcase classname="TestNGPack.VerifyLoginPage" name="verifyForgotPasswordLinkOnLoginPage" time="9.416">
    <failure message="expected [https://www.facebook.com/] but found [https://www.facebook.com/recover/initiate/?privacy_mutation_token=eyJ0eXBlIjowLCJjcmVhdGlvbl90aW1lIjoxNjgwMjQ3NjE0LCJjYWxsc2l0ZV9pZCI6MzgxMjI5MDc5NTc1OTQ2fQ%3D%3D&amp;ars=facebook_login]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.facebook.com/] but found [https://www.facebook.com/recover/initiate/?privacy_mutation_token=eyJ0eXBlIjowLCJjcmVhdGlvbl90aW1lIjoxNjgwMjQ3NjE0LCJjYWxsc2l0ZV9pZCI6MzgxMjI5MDc5NTc1OTQ2fQ%3D%3D&ars=facebook_login]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at TestNGPack.VerifyLoginPage.verifyForgotPasswordLinkOnLoginPage(VerifyLoginPage.java:151)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyForgotPasswordLinkOnLoginPage -->
  <system-out/>
  <testcase classname="TestNGPack.VerifyLoginPage" name="verifyCreateNewAccountButtonOnLoginPage" time="0.000">
    <skipped/>
  </testcase> <!-- verifyCreateNewAccountButtonOnLoginPage -->
  <system-out/>
  <testcase classname="TestNGPack.VerifyLoginPage" name="verifyCreateNewAccountButtonOnLoginPage" time="0.000">
    <skipped/>
  </testcase> <!-- verifyCreateNewAccountButtonOnLoginPage -->
  <system-out/>
  <testcase classname="TestNGPack.VerifyLoginPage" name="verifyCreateNewAccountButtonOnLoginPage" time="0.000">
    <skipped/>
  </testcase> <!-- verifyCreateNewAccountButtonOnLoginPage -->
  <system-out/>
</testsuite> <!-- TestNGPack.VerifyLoginPage -->
